# Image: https://odin.s0.no/2016/glowing-bear-weechat-client-screenshot.png
VideoControls-chat-button = Chat
VideoControls-leave-button = Leave
VideoControls-leave-button-menu-end-meeting = End meeting for all
VideoControls-leave-button-menu-leave = Leave room
VideoControls-leave-button-menu-leave-group = Leave group
VideoControls-people-button = People
VideoControls-people-button-menu-breakout-groups = Breakout Groups
VideoControls-people-button-menu-breakout-groups-end = End breakout session
VideoControls-people-button-menu-breakout-groups-new-badge = New
VideoControls-people-button-menu-people = People
VideoControls-record-button-menu-get = Get recordings
VideoControls-record-button-menu-header = Recording
VideoControls-record-button-menu-start = Start recording
VideoControls-record-button-menu-stop = Stop recording
VideoControls-record-button-start = Record
VideoControls-record-button-stop = Stop
VideoControls-share-button-menu-configure = Configure integrations
VideoControls-share-button-menu-screenshare = Screenshare
VideoControls-share-button-menu-share-integration-about-integrations = About integrations
VideoControls-share-button-menu-share-integration-fullscreen = Fullscreen
VideoControls-share-button-menu-share-integration-maximize = Maximize
VideoControls-share-button-menu-share-integration-minimize = Minimize
VideoControls-share-button-menu-share-integration-stop = Stop {$title}
VideoControls-share-button-menu-share-screen-start = Share screen
VideoControls-share-button-menu-share-screen-stop = Stop screenshare
VideoControls-share-button-menu-started-by = Started by {$displayName}
VideoControls-share-button-menu-started-by-you = Started by you
VideoControls-share-button-start = Share
VideoControls-share-button-stop = Stop
VideoControls-stream-button-menu-header = Streaming
VideoControls-stream-button-menu-start = Start streaming
VideoControls-stream-button-menu-stop = Stop streaming
VideoControls-stream-button-start = Stream
VideoControls-stream-button-stop = Stop
VideoControls-toggle-cam-button = Cam
VideoControls-toggle-cam-button-menu-mute = Turn cam off
VideoControls-toggle-cam-button-menu-settings = Video settings
VideoControls-toggle-cam-button-menu-unmute = Turn cam on
VideoControls-toggle-mic-button = Mic
VideoControls-toggle-mic-button-menu-mute = Mute mic
VideoControls-toggle-mic-button-menu-settings = Audio settings
VideoControls-toggle-mic-button-menu-unmute = Unmute mic
